Repository GED-Extensao-ADS-4/front-ged-app, pull requests merged in 2024-12, with the labels that each got.

#10 🐛 fix: upd tipo CardProps.icone em comnponents/Home/Card
  src/components/Home/Card.tsx
Labels: bug

#12 Raphae alert modals
  src/components/modals/ModalGenerico.tsx
  src/pages/Home.tsx
Labels: melhoria

#11 feat: atualizar em relação à main
  src/components/Home/Card.tsx
  src/components/modals/ModalGenerico.tsx
  src/pages/Home.tsx
Labels: bug

#22 feat: inativar alunos
  src/pages/alunos/HomeAlunos.tsx
Labels: melhoria

#29 feat: CRUD alunos
  src/App.tsx
  src/assets/css/pages/aluno.css
  src/assets/css/style.css
  src/assets/css/variaveis.css
  src/components/common/Botao.tsx
  src/components/common/Icone.tsx
  src/components/layout/Layout.tsx
  src/components/modals/InativarAlunoModal.tsx
  src/components/modals/ModelCadastrarAluno.tsx
  src/helpers/formatarCPF.ts
  src/helpers/formatarData.ts
  src/models/Aluno.ts
  src/pages/Home.tsx
  src/pages/alunos/Home.tsx
  src/pages/alunos/HomeAlunos.tsx
  src/routes/RotasPrivadas.tsx
  src/services/api.ts
Labels: melhoria

#33 ✨ feat: corrigir tudo
  package.json
  src/App.tsx
  src/assets/css/pages/aluno.css
  src/assets/css/pages/documentos.css
  src/assets/css/pages/header.css
  src/assets/css/style.css
  src/assets/css/variaveis.css
  src/components/Home/Card.tsx
  src/components/alunos/SelectAlunos.tsx
  src/components/alunos/SelectEstados.tsx
  src/components/common/Botao.tsx
  src/components/common/Icone.tsx
  src/components/documentos/SelectDocumentos.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/modals/InativarAlunoModal.tsx
  src/components/modals/ModelCadastrarAluno.tsx
  src/helpers/formatarCPF.ts
  src/helpers/formatarData.ts
  src/models/Aluno.ts
  src/models/Documentos.ts
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/alunos/Aluno.tsx
  src/pages/alunos/Home.tsx
  src/pages/alunos/HomeAlunos.tsx
  src/pages/documentos/DocumentosCadastro.tsx
  src/pages/documentos/DocumentosPage.tsx
  src/routes/RotasPrivadas.tsx
  src/services/api.ts
Labels: melhoria

#34 📝 docs: add autores e funcionalidades ao README.md
  README.md
Labels: documentacao
